
var questions = [
        {
            question: "How many starter Pokemons can you choose from?",
            a: "1",
            b: "3",
            c: "5",
            answer: 2,
            category: "Pokemon",
        },
        {
          question: "What color is Charmander?",
          a: "Green",
          b: "Blue",
          c: "Orange",
          answer: 3,
          category: "Pokemon",
        },
        {
          question: "Which is not a legendary Pokemon?",
          a: "Heatran",
          b: "Dragonite",
          c: "Lugia",
          answer: 2,
          category: "Pokemon",
        },
        {
          question: "Which is a Minecraft character?",
          choice1: "Creeper",
          choice2: "Crawler",
          choice3: "Crowbar",
          answer: 1,
          category: "Minecraft",
        },
        {
          question: "Who created Minecraft?",
          choice1: "Anders Jansson",
          choice2: "Johan Larsson",
          choice3: "Markus Persson",
          answer: 3,
          category: "Minecraft",
        },
        {
          question: "What shape are building blocks?",
          choice1: "square",
          choice2: "circular",
          choice3: "hexagon",
          answer: 1,
          category: "Minecraft",
        },
        {
            question: "What is 3x3",
            choice1: "9",
            choice2: "18",
            choice3: "35",
            answer: 1,
            category: "Maths",
        },
        {
          question: "What is 24 - 8",
          choice1: "16",
          choice2: "13",
          choice3: "19",
          answer: 1,
          category: "Maths",
        },
        {
            question: "What is 4-4",
            choice1: "2",
            choice2: "16",
            choice3: "0",
            answer: 3,
            category: "Maths",
        }
      ];